export const SET_PRODUTO = 'SET_PRODUTO'
export const CLEAR_PRODUTO = 'CLEAR_PRODUTO'
export const SET_LISTA_PRODUTOS = 'SET_LISTA_PRODUTOS'
export const CLEAR_LISTA_PRODUTOS = 'CLEAR_LISTA_PRODUTOS'
